sudo: false
os:
  - linux
  - osx
  - windows
  - freebsd

language: go
go: 
 - 1.5
 - tip

before_install:
 - export PATH=/home/travis/gopath/bin:$PATH

install:
 - go get ./...
 
script:
 - go test ./...
